apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello
  namespace: argocd
spec:
  project: default
  source:
    repoURL: oci://ghcr.io/aaronshemtovit      # OCI registry!
    chart: hello-world-ingress
    targetRevision: "0.2.2"                    # same tag as Flux
    helm:
      enableOci: true                          # ← Argo flag
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}
