# hello-application.yaml  (points to same OCI chart)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    chart: hello-world-ingress
    repoURL: oci://ghcr.io/aaronshemtovit
    targetRevision: "0.0.0"              # → workflow bumps this
    helm:
      releaseName: hello-argo
  syncPolicy:
    automated: {}
