apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: nginx
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade   # ← add pre‑upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  controller: k8s.io/ingress-nginx

