apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-ingress-nginx
  namespace: ingress-nginx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-ingress-nginx         # must match Role above
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-ingress-nginx       # must match SA
    namespace: ingress-nginx

