apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-ingress-nginx         # release‑unique
  labels:
    app.kubernetes.io/part-of: ingress-nginx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-ingress-nginx         # must match clusterrole.yaml
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-ingress-nginx       # must match SA
    namespace: ingress-nginx

