apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hello
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: hello-world-ingress
      sourceRef:
        kind: HelmRepository
        name: hello-oci
      version: "0.0.0"          # CI/CD workflow bumps this
  valuesFrom: []               # (optional overrides)
