# hello-source.yaml  (OCI HelmRepository)
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: hello-oci
  namespace: flux-system
spec:
  type: oci
  url: oci://ghcr.io/aaronshemtovit
