apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: hello-oci
  namespace: flux-system
spec:
  type: oci
  url: oci://ghcr.io/aaronshemtovit
  interval: 5m
  secretRef:            # ← add
    name: ghcr-creds