# envs/flux/hello-helmrelease.yaml  (HelmRelease)
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hello
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: hello-world-ingress
      version: "0.2.3"        # ← latest published chart tag
      sourceRef:
        kind: HelmRepository
        name: hello-oci
        namespace: flux-system
