name: Dual‑GitOps‑CD
on:
  workflow_run:
    workflows: ["Helm‑CI"]
    types: [completed]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download packaged chart
        uses: actions/download-artifact@v3
        with:
          name: chart-version

      - name: Extract chart version
        id: ver
        run: |
          VER=$(ls hello-world-ingress-*.tgz | sed 's/.*-\(.*\)\.tgz/\1/')
          echo "VER=$VER" >> $GITHUB_OUTPUT

      # ── Flux ───────────────────────────────────────────────────────────────
      - name: Update Flux HelmRelease
        run: |
          yq -i '.spec.chart.spec.version = "${{ steps.ver.outputs.VER }}"' \
              envs/flux/hello-helmrelease.yaml

      # ── Argo CD ────────────────────────────────────────────────────────────
      - name: Update Argo CD Application
        run: |
          yq -i '.spec.source.helm.version = "${{ steps.ver.outputs.VER }}"' \
              envs/argocd/hello-application.yaml

      - name: Commit + push
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "CI: bump chart to ${{ steps.ver.outputs.VER }}"

  # ── Validation job (runs after GitOps controllers sync) ────────────────────
  validate:
    needs: sync
    runs-on: ubuntu-latest
    env:
      KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
    steps:
      - name: Set up kubectl
        run: |
          echo "$KUBE_CONFIG_DATA" | base64 -d > $HOME/.kube/config
      - name: Wait for Flux + Argo
        run: scripts/wait-release.sh hello-deployment default 300

      - name: Compare manifests
        run: scripts/compare.sh hello fluxcd argocd > tmp/log.txt

      - name: Upload compare log
        uses: actions/upload-artifact@v3
        with:
          name: deploy-compare
          path: tmp/log.txt
